name: Build and Release

on:
  push:
    branches:
      - main
      - 1.20.x

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: List files in build
        run: ls -la build

      - name: List files in build/libs
        run: ls -la build/libs

      - name: Get current date and time
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d-%H.%M')"

      - name: Get version from gradle.properties
        id: get_version
        run: |
          VERSION=$(grep "version=" gradle.properties | cut -d'=' -f2)
          echo "::set-output name=version::$VERSION"

      - name: Get Minecraft Version from gradle.properties
        id: get_mc_version
        run: |
          MC_VERSION=$(grep "mc_version=" gradle.properties | cut -d'=' -f2)
          echo "::set-output name=mc_version::$MC_VERSION"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest-${{ steps.get_branch.outputs.branch }}
          release_name: TelegramSRV ${{ steps.get_branch.outputs.branch }} | Latest Build
          draft: false
          prerelease: false

      - name: Find JAR file
        id: find_jar
        run: |
          JAR_FILE=$(find build/libs -name "*.jar" -print -quit)
          echo "::set-output name=jar_path::$JAR_FILE"

      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.find_jar.outputs.jar_path }}
          asset_name: TelegramSRV-${{ steps.get_mc_version.outputs.branch }}-${{ steps.get_version.outputs.version }}.jar
          asset_content_type: application/java-archive
